version: '2'

volumes:
  mysql_data:
    driver: local

services:
  db:
    image: mysql:latest
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jbpm
      MYSQL_USER: jbpm
      MYSQL_PASSWORD: jbpm
  jbpm:
    image: jboss/jbpm-server-full
    environment:
      JBPM_DB_DRIVER: mysql
      JBPM_DB_HOST: db
    ports:
    - 8080:8080
    - 8001:8001
    depends_on:
    - db
